name: faber_concert_main
description: "photo, video clip, text"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  amplify_flutter: 1.7.0
  amplify_auth_cognito: 1.7.0
  amplify_storage_s3: 1.7.0
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.9
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1

dependency_overrides:
  drift: null # drift 패키지 제거


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
